name: Testando Encoding
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testando encoding
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Arquivos modificados
        id: changed-files
        uses: tj-actions/changed-files@v14.6
      
      - name: Instalando uchardet
        run: sudo apt-get install uchardet -y

      - name: Lista os arquivos modificados
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              encoding=$(uchardet $file) && 
              echo $encoding
              if [ "$encoding" = "ISO-8859-1" ]; then
                  echo "Encoding correto"
              else
                  echo "Encoding inválido no arquivo . "
                  echo $file
                  exit 1
              fi
          done
