name: CI
on: [pull_request, push, workflow_dispatch]

jobs:
  deploy:
    name: "Testando"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Configure SSH
        run: echo ${BASE_BRANCH}
    env:
      BASE_BRANCH: ${{ github.base_ref }}
