name: CI
on: [pull_request, push, workflow_dispatch]

jobs:
  deploy:
    name: "Testando"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Da branch
        run: echo ${github.base_ref}
      - name: Para a branch
        run: echo ${github.head_ref}
