name: CI
on: [pull_request, push, workflow_dispatch, pull_request_review]
#on:
#  pull_request:
#    types:
#      - closed

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Testando encoding
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Arquivos modificados
        id: changed-files
        uses: tj-actions/changed-files@v14.6
      
      - name: Instalando uchardet
        run: sudo apt-get install uchardet -y

      - name: Lista os arquivos modificados
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              encoding=$(uchardet $file) && 
              echo $encoding
              if [ "$encoding" = "ISO-8859-1" ]; then
                  echo "Encoding válidi"
              else
                  echo "Encoding inválilido no arquivo . "
                  echo $file
                  exit 1
              fi
          done
