name: CI
on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: "Set Jira task status to Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Instalando JIRA PHP Lib
        run: composer require lesstif/php-jira-rest-client

      - name: Chandge task to test on jira
        run: |
          php ${GITHUB_WORKSPACE}/.github/jira_issue_test.php $JIRA_HOST $JIRA_TOKEN $JIRA_TASK
        env:
          JIRA_HOST: ${{ secrets.JIRA_HOST }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }} 
          JIRA_TASK: ${{ github.head_ref || github.ref_name }}
