name: CI
on: [pull_request, push, workflow_dispatch]

jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Configure SSH
        run: echo ${{ github.ref_name }}
