name: CI
on: [pull_request, push, workflow_dispatch]

jobs:
  deploy:
    name: "Testando"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Test
        run: echo "${BRANCH_NAME}"
