name: CI
on: [pull_request, push, workflow_dispatch]

jobs:
  deploy:
    name: "Set Jira task status to Test"
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Instalando JIRA PHP Lib
        run: composer require lesstif/php-jira-rest-client

      - name: Chandge task to test on jira
        run: |
          php ${GITHUB_WORKSPACE}/.github/jira-test.php $JIRA_HOST $JIRA_TOKEN
        env:
          JIRA_HOST: https://jira.aisolutions.tec.br/
          JIRA_TOKEN: 5554444
