name: CI
on: [pull_request, push, workflow_dispatch, pull_request_review]
#on:
#  pull_request:
#    types:
#      - closed

jobs:
  deploy:
    name: "Testando"
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || 
    steps:
 
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
 
      - name: Checkout Current Repository
        uses: actions/checkout@v2
        with:
          path: ./source-repo/ 
          ref: 'main'
          
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
